apiVersion: v1
kind: Service
metadata:
  name: app-deployment
  namespace: app-deployment
  labels:
    app: app-deployment
spec:
  selector:
    app: app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
